using CustomerSupport.Application.Models;

namespace CustomerSupport.Application.Interfaces.Files
{
    // Defines the file-storage operations required by the Application layer.
    // The Application layer depends only on this interface and does not know
    // where or how the physical files are stored.
    //
    // Today:
    //      LocalFileStorageService stores files on the local file system.
    //
    // Later:
    //      AzureBlobFileStorageService can implement the same interface
    //      and store files in Azure Blob Storage.
    //
    // Because the Application layer depends on an abstraction rather than
    // a concrete storage technology, changing the storage provider does not
    // require changing the business logic in TicketAttachmentService.
    public interface IFileStorageService
    {
        // Saves the supplied file content to the configured storage provider.
        // content:
        //      Contains the actual file data as a Stream.
        //      Using Stream keeps the Application layer independent of
        //      ASP.NET Core types such as IFormFile.
        //
        // extension:
        //      The validated file extension, for example:
        //      .pdf, .png, .jpg, .docx.
        //
        // ticketId:
        //      Identifies the Ticket to which the file belongs.
        //      The local implementation uses it to organize files
        //      inside a Ticket-specific folder.
        //
        // The method returns information generated by the storage provider,
        // such as:
        //      - Stored file name
        //      - Relative storage path
        //
        // This information can then be saved in the TicketAttachments table.
        Task<StoredFileResult> SaveAsync(Stream content, string extension, int ticketId);

        // Opens an already stored file for reading.
        // relativePath is the storage path saved in SQL Server.
        // The method returns:
        //      - A readable Stream when the physical file exists.
        //      - null when the physical file cannot be found.
        //
        // Returning a Stream allows the API Controller to send the file
        // directly to the client without loading the complete file into memory.
        Task<Stream?> OpenReadAsync(string relativePath);

        // Deletes a physical file from the configured storage provider.
        // This operation is mainly required for cleanup.
        // For example:
        // 1. The file is successfully written to local storage.
        // 2. The database operation fails.
        // 3. We should delete the physical file so that an orphan file
        //    is not left behind on the server.
        Task DeleteAsync(string relativePath);
    }
}